/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// For BRAT Installation
// The full compiled main.js content needs to be here

// IMPORTANT NOTE:
// The actual file is quite large (842KB) and would normally be included here
// When installing with BRAT, please use the GitHub release which includes
// the complete compiled main.js file

// This file is a reference/pointer to the GitHub release
// BRAT installation URL: https://github.com/excelsier/obsidian-oh-my-cv/releases